language: objective-c

osx_image: xcode8.0
xcode_sdk: iphonesimulator10.0

before_install:
  - gem install specific_install
  - gem specific_install -l https://github.com/venmo/slather.git
  
script:
- set -o pipefail && xcodebuild test -workspace Example/JModalController.xcworkspace -scheme JModalController-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

after_success:
  - cd $TRAVIS_BUILD_DIR && slather
